### ISSUE TITLE
min-stability dev should be stable

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-installer#100]
Setting min-stability = dev breaks developer expectations and makes the use of composer more error prone. 

A couple of examples of the issues this causes:

 * You can't install silverstripe/translatable without specifying a version explicitly, as it will try and grab the 4.0-only version of the module. Although this is a bug in composer (https://github.com/composer/composer/issues/4181) I think that one of the reason the bug slipped through is that most people don't set min-stability = dev. We're being unorthodox and our users are paying the price.
 * Our projects frequently run with dev versions of composer/installers and phpunit. This makes no sense.
 * Feedback from someone at DPC conference today: "I keep being asked to install SilverStripe 4.0, it was very confusing, why are you recommending the development version?"

The reason we've selected min-stability = dev is because so many addons don't produce stable modules. We should address that problem head-on, and get stable releases out for more modules.

A "stable release" can be as simple as creating the tag—I think it's counterproductive to say that we need to keep installing dev modules because there's no time to create stable releases. If we're seriously unsure about stability, we could create a `0.x.y` release.

We'll need to put out some comms to module developers. In my view, 3.2 stable would be a good time to do this.

There's an open question with pre-release versions: arguably, it makes sense to install pre-release packages of modules in pre-release versions of SilverStripe. I'm not sure of the best way to manage this.

**Comment by dhensby** [comment]
I agree we should be using stable modules.

I think we should encourage module developers to tag releases and adopt semver as this makes version constraints far more predictable.

We have to avoid the use of "*" as our requirement for any module and lock onto ones where the API is compatible for the version in question.

Perhaps `prefer-stable: true` is a good compromise, rather than disallowing dev deps completely? (https://getcomposer.org/doc/04-schema.md#prefer-stable)

**Comment by sminnee** [comment]
Good all on prefer-stable. I'm making a pull request.
