### ISSUE TITLE
SS4 installer: environment variables help link incorrectly routes to SS3 docs

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-installer#184]
Quick note: In the Database Configuration section of the installer, the help link associated with the "Use environment variables for configuration" checkbox routes user to old SS3 _ss_environment.php docs.

**Comment by robbieaverill** [comment]
@SpiritLevel this is happening because [the documentation links](https://github.com/silverstripe/silverstripe-framework/blob/master/src/Dev/Install/config-form.html#L49) omit a specific version. This would be "fixed" when SS4 becomes the stable version, however it would also probably require a patch to the 3.x release line to add the `3` version to the URL so it doesn't bring back 4.x results

**Comment by SpiritLevel** [comment]
Hmmm...it would be good if any instance of SilverStripe could determine its own version and use this to link to any corresponding documentation.

**Comment by chillu** [comment]
Yeah, it's a minor annoyance, but I don't think introducing the complexity of either hardcoding version numbers (and forgetting to update them) or determinining them during archive build somehow is worth the effort for the core team - closing. Keen to hear ideas on how to e.g. improve http://github.com/silverstripe/cow to auto-update and commit to installer on new major releases, but they'd need to be followed up by pull requests from the community :)
