### ISSUE TITLE
ERROR [Emergency]: Uncaught TypeError: Return value of Symfony\Component\Filesystem\Filesystem::toIterable() must be an instance of (...)

### ISSUE THREAD

**Issue by rbaarsma** [silverstripe/silverstripe-installer#239]
When doing a fresh install I get multiple errors, the first of which is in the title of this bug post.

see https://github.com/silverstripe/silverstripe-asset-admin/issues/703

Basically symfony/filesystem requires php version 7.1.3 or higher.

So simply add "php": "^7.1.3" to composer.json to fix this for others

**Comment by rbaarsma** [comment]
Related to https://github.com/silverstripe/cow/issues/65

**Comment by robbieaverill** [comment]
Have you installed using one of the archive files from the SilverStripe website? If so, they can be built for PHP 7. You can run `composer update` from within your project to downgrade these dependencies to PHP 5.6 compatible versions if you're not running PHP 7. I'm going to close this because we have a couple of duplicates at the moment, but thanks for raising the issue
