### ISSUE TITLE
The file install.php is missing. Is that on purpose?

### ISSUE THREAD

**Issue by kalicki2k** [silverstripe/silverstripe-installer#268]
With Silverstripe version 4.5.0 I noticed that there is no more install.php. Now I wonder if this is intentional and how I can install Silverstripe now?

**Comment by robbieaverill** [comment]
Hi @kalicki2k, yes this was intentional. You can install SilverStripe with Composer: `composer create-project silverstripe/installer my-project`, or you can use the [SilverStripe Installer wizard](https://github.com/silverstripe/silverstripe-installer-wizard), which is now a separate package.

Background info: https://github.com/silverstripe/silverstripe-framework/issues/9195 https://github.com/silverstripe/silverstripe-framework/pull/9231

Happy festive season!
