### ISSUE TITLE
 Could not find package silverstripe/installer with version 4.12.3.

### ISSUE THREAD

**Issue by GaneshKandu** [silverstripe/silverstripe-installer#352]
Hi,

I noticed a new release available in SilverStripe, I am trying to install SilverStripe 4.12.3 using Composer install, but I am facing an issue while installing.

 Could not find the package silverstripe/installer with version 4.12.3.

![image](https://user-images.githubusercontent.com/12833130/229045592-b6c0ae04-703e-4e82-b99d-55ed50cd5a68.png)

its also not released in [github ](https://github.com/silverstripe/silverstripe-installer/tags)

**Comment by emteknetnz** [comment]
I'm not sure why you're trying to install 4.12.3 when the latest stable version in 4.12.1

Why are you trying to install 4.12.3?

**Comment by GaneshKandu** [comment]
> Why are you trying to install 4.12.3?

![image](https://user-images.githubusercontent.com/12833130/229410451-b8f32fad-0349-497f-87c9-ef1d78eea8c8.png)

## you mean 4.12.3 is not stable ?

**Comment by emteknetnz** [comment]
Oh right, seems like that page is getting the version number from [silverstripe/framework](https://github.com/silverstripe/silverstripe-framework/) instead of [silverstripe/installer](https://github.com/silverstripe/silverstripe-installer)

Just use the `composer create-project` command on the page and you'll get the latest version of silverstripe/installer on your local
